import "./globals.css";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
      <Header/>
      <main className="flex-grow">
        {children}
      </main>
      <Footer/>
      </body>
    </html>
  );
}